// <auto-generated />
using System;
using BabyTracker2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BabyTracker2.Migrations
{
    [DbContext(typeof(BabyTracker2Context))]
    partial class BabyTracker2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BabyTracker2.Models.BabyInfo", b =>
                {
                    b.Property<int>("BabyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BabyGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BabyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BabyID");

                    b.HasIndex("UserID");

                    b.ToTable("BabyInfo");
                });

            modelBuilder.Entity("BabyTracker2.Models.BabyMileStone", b =>
                {
                    b.Property<int>("MileStoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BabyID")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("MileStoneID");

                    b.HasIndex("BabyID");

                    b.ToTable("BabyMileStone");
                });

            modelBuilder.Entity("BabyTracker2.Models.DiaperChange", b =>
                {
                    b.Property<int>("NumberofDiaperChanges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BabyID")
                        .HasColumnType("int");

                    b.HasKey("NumberofDiaperChanges");

                    b.HasIndex("BabyID");

                    b.ToTable("DiaperChange");
                });

            modelBuilder.Entity("BabyTracker2.Models.Feeding", b =>
                {
                    b.Property<int>("FeedingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BabyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfFeedings")
                        .HasColumnType("int");

                    b.HasKey("FeedingID");

                    b.HasIndex("BabyID");

                    b.ToTable("Feeding");
                });

            modelBuilder.Entity("BabyTracker2.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BabyTracker2.Models.BabyInfo", b =>
                {
                    b.HasOne("BabyTracker2.Models.Users", "Users")
                        .WithMany("BabyInfos")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BabyTracker2.Models.BabyMileStone", b =>
                {
                    b.HasOne("BabyTracker2.Models.BabyInfo", "BabyInfo")
                        .WithMany("BabyMileStones")
                        .HasForeignKey("BabyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BabyTracker2.Models.DiaperChange", b =>
                {
                    b.HasOne("BabyTracker2.Models.BabyInfo", "BabyInfo")
                        .WithMany("DiaperChanges")
                        .HasForeignKey("BabyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BabyTracker2.Models.Feeding", b =>
                {
                    b.HasOne("BabyTracker2.Models.BabyInfo", "BabyInfo")
                        .WithMany("Feedings")
                        .HasForeignKey("BabyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
