// <auto-generated />
using System;
using BabyTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BabyTracker.Migrations
{
    [DbContext(typeof(BabyTrackerContext))]
    [Migration("20200512152633_Addd BabyInfo model")]
    partial class AdddBabyInfomodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BabyTracker.Models.BabyInfo", b =>
                {
                    b.Property<int>("BabyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BabyGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BabyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("int");

                    b.HasKey("BabyID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("BabyInfo");
                });

            modelBuilder.Entity("BabyTracker.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BabyTracker.Models.BabyInfo", b =>
                {
                    b.HasOne("BabyTracker.Models.Users", "Users")
                        .WithMany("BabyInfos")
                        .HasForeignKey("UsersUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
